 # 1.Perform arithmetic operations on NumPy arrays.


In [4]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
result_add=a+b
result_sub=a-b
result_mul=a*b
result_div=a/b
result_pow=a**b
result_mod=a%b
print("addition :",result_add)
print("subtract :",result_sub)
print("multiplication :",result_mul)
print("division :",result_div)
print("power :",result_pow)
print("modulus: ",result_mod)


addition : [ 6  8 10 12]
subtract : [-4 -4 -4 -4]
multiplication : [ 5 12 21 32]
division : [0.2        0.33333333 0.42857143 0.5       ]
power : [    1    64  2187 65536]
modulus:  [1 2 3 4]


 # 2.Write a script to compute the mean and standard deviation of a NumPy array

In [6]:
a = np.array([10, 20, 30, 40, 50])
mean_ = np.mean(a)
print("Mean:", mean_)
std_dev = np.std(a)
print("Standard Deviation:", std_dev)


Mean: 30.0
Standard Deviation: 14.142135623730951


# 3.Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [7]:
a=np.arange(10,51,5)
print(a)

[10 15 20 25 30 35 40 45 50]


 # 4.Reshape the array into a 2x4 matrix.

In [11]:
a=np.arange(10,51,5)
reshaped_array = a[0:8].reshape(2, 4)  # Use the first 8 elements
print("Reshaped Array (2x4):" ,reshaped_array)

Reshaped Array (2x4): [[10 15 20 25]
 [30 35 40 45]]


# 5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.

• Replace all elements greater than 4 with 0.

In [20]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
sub_matrix=arr[1:,:2]
print("submatrix:",sub_matrix)
arr[arr>4]=0
print("replaced matrix: ",arr)

submatrix: [[4 5]
 [7 8]]
replaced matrix:  [[1 2 3]
 [4 0 0]
 [0 0 0]]


# 6.Create two 1D arrays:
• a = np.array([1, 2, 3])

• b = np.array([4, 5, 6])

• Perform element-wise addition, multiplication, and division.

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition = a + b
print("Element-wise Addition:", addition)
multiplication = a * b
print("Element-wise Multiplication:", multiplication)
division = a / b
print("Element-wise Division:", division)


Element-wise Addition: [5 7 9]
Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]


# 7.Create a random NumPy array of size (4, 4). Compute:

• Mean of each column.

• Maximum value of the entire array.

• Sum of all elements.

In [43]:
array=np.random.rand(4,4)
print("random numpyarray: ",array)
mean_col=np.mean(array,axis=0)
print("mean_column: ",mean_col)
max_value=np.max(array)
print("maximum value: ",max_value)
sum_all=np.sum(array)
print("sum of all elements:",sum_all)


random numpyarray:  [[0.29571501 0.45788999 0.00802737 0.49997316]
 [0.59182493 0.33145829 0.25481705 0.55196535]
 [0.15630978 0.17190585 0.86592642 0.05844876]
 [0.20574189 0.43306274 0.77038091 0.84368904]]
mean_column:  [0.3123979  0.34857922 0.47478794 0.48851907]
maximum value:  0.8659264242951824
sum of all elements: 6.497136537126158


# 8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [30]:
arr=np.array([1,2,3,4])
result=(arr+10)*2
print(result)

[22 24 26 28]


# 9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:

• Extract the second "layer" (i.e., the second 2D array) in the first dimension.

• Extract the first two rows and the last three columns from each "layer."

• Replace all elements divisible by 3 with -1.

In [41]:
arr = np.random.randint(1, 101, size=(3, 4, 5))
print("Original 3D Array:",arr)
sec_lay=arr[1]
print("\nsecond layer: ",sec_lay)
extracted_data = arr[:, :2, 2:]
print("\nFirst two rows and last three columns from each layer:")
print(extracted_data)
arr[arr % 3==0]=-1
print("\n replaced array :",arr)

Original 3D Array: [[[52 35 99 12 91]
  [96 95 57 27 95]
  [82 88 27 59 18]
  [34 76 46 10 64]]

 [[48 28 70 20 79]
  [73 41 88 15 60]
  [44 32 17  9 85]
  [96 31 55 52 31]]

 [[26 74 61 51 11]
  [88 14 22 98 79]
  [70 97 44 18 94]
  [73 97 88 82 69]]]

second layer:  [[48 28 70 20 79]
 [73 41 88 15 60]
 [44 32 17  9 85]
 [96 31 55 52 31]]

First two rows and last three columns from each layer:
[[[99 12 91]
  [57 27 95]]

 [[70 20 79]
  [88 15 60]]

 [[61 51 11]
  [22 98 79]]]

 replaced array : [[[52 35 -1 -1 91]
  [-1 95 -1 -1 95]
  [82 88 -1 59 -1]
  [34 76 46 10 64]]

 [[-1 28 70 20 79]
  [73 41 88 -1 -1]
  [44 32 17 -1 85]
  [-1 31 55 52 31]]

 [[26 74 61 -1 11]
  [88 14 22 98 79]
  [70 97 44 -1 94]
  [73 97 88 82 -1]]]


# 10. Work with broadcasting and advanced operations in NumPy.
Create a NumPy array arr of shape (3, 3) with random integers between  
1 and 20. Perform the following:

• Subtract the mean of each row from its respective elements (row-wise
normalization).

• Create a new array by squaring all the elements in arr.

• Find the indices of the top 3 maximum values in the entire array.

In [44]:
arr = np.random.randint(1, 21, size=(3, 3))
print(" Array is:",arr)
row_mean = arr.mean(axis=1, keepdims=True)
org_arr = arr - row_mean
print("\nRow-wise Normalized Array:",org_arr)
square_arr = arr ** 2
print("\nSquaring array:",square_arr)
top3_indices = np.unravel_index(np.argsort(arr.ravel())[-3:], arr.shape)
print("\nIndices of Top 3 Maximum Values:",top3_indices)


 Array is: [[18  1  8]
 [ 4 18  9]
 [15 13 18]]

Row-wise Normalized Array: [[ 9.         -8.         -1.        ]
 [-6.33333333  7.66666667 -1.33333333]
 [-0.33333333 -2.33333333  2.66666667]]

Squaring array: [[324   1  64]
 [ 16 324  81]
 [225 169 324]]

Indices of Top 3 Maximum Values: (array([0, 1, 2]), array([0, 1, 2]))
